[[maven-archetype]]

////
a=&#225; e=&#233; i=&#237; o=&#243; u=&#250;

A=&#193; E=&#201; I=&#205; O=&#211; U=&#218;

n=&#241; N=&#209;
////

== ARCHETYPE

An archetype is an Apache Maven template (or a blueprint, if you prefer);
it can contain files and folders, any content is allowed; the only mandatory element is the root pom.xml.

The Maven Archetype Plugin available at http://maven.apache.org/archetype/maven-archetype-plugin/
delivers all goals that you need to handle this type of artifact:

* generate: It creates a Maven project, given the archetype's coordinates that are passed via the command line.
  If coordinates are not specified, Maven will show a list of archetypes available on Maven Central and will interactively
  let the user choose which archetype to use.

* create-from-project: It can be executed from the root of any Maven project; it generates an artifact
  (in target/generated-source/archetype) containing the archetype with the structure and contents of the current Maven project.

Every Maven Repository can be requested to deliver the complete list of archetypes hosted just by running the following command:

 mvn archetype:generate \
  -DarchetypeCatalog=http://artifacts.mysite.com/repository/archetype-catalog.xml

If the property archetypeCatalog is not set, the Maven Central Repository will be used,
showing a list of more than 700 archetypes (you may want to search "archetype" on http://search.maven.org first.

